openapi: 3.0.3
info:
  title: TA1 Object Supplements
  description: |-
    This contains certain objects required for sending probe responses and receiving alignment scores from TA1, but are not required for TA3 clients.

    The API is based on the OpenAPI 3.0 specification.
  version: 0.2.2
servers:
- url: /
paths:
 /no/path:
    get:
      description: Do not use this; this is here because paths can't be blank
      operationId: noPath
      responses:
        "200":
          description: "Successful operation"
          content:
            text/plain:
              schema:
                type: string
                x-content-type: text/plain
components:
  schemas:
    ProbeResponse:
      required:
      - choice
      - probe_id
      - scenario_id
      type: object
      properties:
        scenario_id:
          type: string
          description: globally unique scenario ID
        probe_id:
          type: string
          description: globally unique probe ID
        choice:
          type: string
          description: id of choice made
        justification:
          type: string
          description: A justification of the response to the probe
      description: encapsulates the selection by a DM of an option in response to
        a probe
