openapi: 3.0.3
info:
  title: ITM MVP TA3 API
  description: |-
    This is the specification of a proposed TA3 API for the In The Moment (ITM) Minimum Viable Product (MVP).  Currently, there is an Evaluation API for TA2 and a preliminary scenario/probe submission API for TA1 that won't be used in the MVP, and currently lacks an API regarding sending probe responses and receiving alignment scores from TA1.

    The API is based on the OpenAPI 3.0 specification.

    Some aspects of this API are not necessarily planned to be implemented for MVP, but show the direction we are heading.
  version: 0.2.2
servers:
- url: /
paths:
 /no/path:
    get:
      description: Do not use this, this is here because paths cant be blank
      operationId: noPath
      responses:
        "200":
          description: "Successful operation, api key returned"
          content:
            text/plain:
              schema:
                type: string
                x-content-type: text/plain
components:
  schemas:
    Probe:
      required:
      - id
      - prompt
      - scenario_id
      - type
      type: object
      properties:
        id:
          type: string
          description: globally unique probe ID
        scenario_id:
          type: string
          description: scenario ID this probe is for
        type:
          type: string
          description: TAs will need to agree on the types of questions being asked;
            only MultipleChoice is supported for MVP
          enum:
          - MultipleChoice
          - FreeResponse
          - PatientOrdering
        prompt:
          type: string
          description: a plain text natural language question for the DM
          example: Which casualty do you treat first?
        state:
          $ref: 'swagger.yaml#/components/schemas/State'
        options:
          type: array
          description: the list of valid choices for the DM to choose among
          items:
            $ref: '#/components/schemas/ProbeOption'
      description: a question for the DM regarding course of action within the scenario.
      example:
        options:
        - kdma_association:
            denial: "+"
            mission: "-"
          id: id
          value: Choice 5
        - kdma_association:
            denial: "+"
            mission: "-"
          id: id
          value: Choice 5
        id: id
        state:
          mission:
            unstructured: Protect the high value intelligence officer.
            mission_type: ProtectVIP
          environment:
            noise_ambient: 0.5
            visibility: 0.5
            aidDelay: 40
            unstructured: unstructured
            weather: sunny
            location: dry desert region
            noise_peak: 0.8
          supplies:
          - quantity: 4
            type: Combat Gauze
          - quantity: 4
            type: Combat Gauze
          unstructured: unstructured
          threat_state:
            unstructured: No additional threats are detected.
            threats:
            - key: threats
            - key: threats
          scenario_complete: false
          casualties:
          - assessed: false
            injuries:
            - severity: 0.8
              name: bicep puncture
              location: right arm
            - severity: 0.8
              name: bicep puncture
              location: right arm
            unstructured: unstructured
            name: Mary
            id: id
            tag: delayed
            vitals:
              RR: 40
              SpO2%: 95
              pain: 8
              mmHg: 180
              hrpmin: 150
            demographics:
              sex: F
              rank: Military
              age: 32
          - assessed: false
            injuries:
            - severity: 0.8
              name: bicep puncture
              location: right arm
            - severity: 0.8
              name: bicep puncture
              location: right arm
            unstructured: unstructured
            name: Mary
            id: id
            tag: delayed
            vitals:
              RR: 40
              SpO2%: 95
              pain: 8
              mmHg: 180
              hrpmin: 150
            demographics:
              sex: F
              rank: Military
              age: 32
          elapsedTime: 5.2
        type: MultipleChoice
        prompt: Which casualty do you treat first?
        scenario_id: scenario_id
    ProbeOption:
      required:
      - id
      - value
      type: object
      properties:
        id:
          type: string
          description: "the choice id, having scenario scope"
        value:
          type: string
          description: a label for the choice
          example: Choice 5
        kdma_association:
          type: object
          additionalProperties:
            type: string
          description: KDMA association of this option; always omitted in TA2 API.
      description: an option associated with a probe.
      example:
        kdma_association:
          denial: "+"
          mission: "-"
        id: id
        value: Choice 5
    ProbeResponse:
      required:
      - choice
      - probe_id
      - scenario_id
      type: object
      properties:
        scenario_id:
          type: string
          description: globally unique scenario ID
        probe_id:
          type: string
          description: globally unique probe ID
        choice:
          type: string
          description: id of choice made (from ProbeOption)
        justification:
          type: string
          description: A justification of the response to the probe
      description: encapsulates the selection by a DM of an option in response to
        a probe
